### ISSUE TITLE
Frontend aufsetzen

### ISSUE THREAD

**Issue by mrdanf** [Smart-City-SoSe-2022/Stadtverwaltung#5]
Epic: #2 

Das Frontend soll installiert und eingerichtet werden.

- [x] Frontend Software und Packages installieren
- [x] Hello World anzeigen
- [ ] Frontend mit Backend verknüpfen (Optional)
- [ ] Hello World durch Backend Logik anzeigen (Optional)

**Comment by VadimB05** [comment]
done
