### ISSUE TITLE
 Docker Container Software herunterladen und installieren

### ISSUE THREAD

**Issue by mrdanf** [Smart-City-SoSe-2022/Stadtverwaltung#6]
Die Docker Container Software aus dem Internet herunterladen und installieren.
RabbitMQ wird bei jedem Lokal in einem Docker Container ausgeführt, damit die Funktionalität mit RabbitMQ beim Programmieren richtig getestet werden kann. Im Repo Dokumentation wird es ein branch geben zur Einrichtung von RabbitMQ im eigenen Docker Container.

**Comment by VadimB05** [comment]
Docker installiert
